const data = {
    products: [
        {
            _id: '1',
            name: 'Blue Large sea',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 65,
            countInStock: 6,
            brand: 'Yobbaalè',
            rating: 4.5,
            numReviews: 8,
            description: 'Très bonne qualité !',
        },
        {
            _id: '2',
            name: 'Tchaya',
            category: 'Pants',
            image: '/images/p2.jpg',
            price: 50,
            countInStock: 6,
            brand: 'V. Cleef',
            rating: 5,
            numReviews: 16,
            description: 'Le must !',
        },
        {
            _id: '3',
            name: 'White cotton',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 125,
            countInStock: 6,
            brand: 'H. Boss',
            rating: 4.5,
            numReviews: 10,
            description: 'Très bonne qualité. A essayer !',
        },
        {
            _id: '4',
            name: 'White Classic',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 60,
            countInStock: 6,
            brand: 'Angela',
            rating: 4,
            numReviews: 8,
            description: 'Très bonne qualité !',
        },
        {
            _id: '5',
            name: 'Deep Blue',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 80,
            countInStock: 6,
            brand: 'Yobbaalè',
            rating: 4.5,
            numReviews: 3,
            description: 'A porter avec un blue jean !',
        },
        {
            _id: '6',
            name: 'Shorty',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 90,
            countInStock: 6,
            brand: 'Yobbaalè',
            rating: 4,
            numReviews: 9,
            description: 'Port agréable. Restez classe !',
        },
        {
            _id: '7',
            name: 'Scottish Lamberjack',
            category: 'Shirts',
            image: '/images/p7.jpg',
            price: 100,
            countInStock: 6,
            brand: 'Maye',
            rating: 5,
            numReviews: 7,
            description: 'Qualité imbattable !',
        },
        {
            _id: '8',
            name: 'White angel',
            category: 'Shirts',
            image: '/images/p8.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Y. Lee',
            rating: 4.5,
            numReviews: 10,
            description: 'Une blancheur éclatante !',
        }
    ],
};

export default data;